### ISSUE TITLE
Соответствие тестов в системе с проектом на Unity

### ISSUE THREAD

**Issue by nk2IsHere** [Lukaviy/AI-for-defense#1]
Было сделано несколько реализаций ICannonAI, используя этот проект.
На Unity (с использованием ограничений , предоставленных в проекте или с использованием ограничений из тестов и увеличением силы, придаваемой CannonBall) все тесты проходятся.
На тестирующей системе же WA 1.
Возникают вопросы: соответствует ли этот проект на Unity тестам в тестирующей системе; изменяется ли скорость выстрела каждый раз?

**Comment by Lukaviy** [comment]
Тесты в тестирующей системе и в проекте различаются. Учтите, что вам не дана сила притяжения в игре. Она может быть разной.
Начальная скорость снаряда постоянна в пределах одного теста. Но в разных тестах может различаться. 
Один тест - попытка поразить одну цель.
Как только цель была поражена, или все боеприпасы израсходовались, тест завершается.
В новом тесте, программа будет запущена заново, а количество снарядов восстановлено.

**Comment by nk2IsHere** [comment]
гравитация также различается только в разных тестах?

**Comment by Lukaviy** [comment]
Да. Все параметры: гравитация, начальная скорость снаряда, расстояние до цели - константы в пределах одного теста. Но могут меняться от теста к тесту.
